
# This file originally has been generated by 'rails generate rspec:install'.

ENV["RAILS_ENV"] ||= 'test'

# This is needed to have activerecord running.
require 'rails/all'

require 'rspec/rails'
require 'rspec/autorun'

# This simulates a database environment. Thus, we don't need a separate test app.
require "with_model"

RSpec.configure do |config|

  # with_model: This simulates the database structure. 
  # Have a look into the spec files to see how it works.
  config.extend WithModel

end

# The simulated database lives in the memory rather than in a file.
ActiveRecord::Base.establish_connection( :adapter => "sqlite3", :database => ":memory:" )

