
# This file originally has been generated by 'rails generate rspec:install'.

ENV["RAILS_ENV"] ||= 'test'

# This is needed to have activerecord running.
require 'rails/all'

require 'rspec/rails'
require 'rspec/autorun'

require 'acts-as-dag'
require 'rails3_acts_as_paranoid'
require 'acts_as_paranoid_dag'


RSpec.configure do |config|
end


# The simulated database lives in the memory rather than in a file.
ActiveRecord::Base.establish_connection( :adapter => "sqlite3", :database => ":memory:" )


# This is the required database structure.
load File.dirname( __FILE__ ) + '/support/schema.rb'


